### ISSUE TITLE
[EXPIRED] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [frohoff/ciphr#7]
Dear Chris,
Could you be so kind to generate ```.exe``` for the rest of us who use Windows, if possible?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by frohoff** [comment]
I'm not terribly familiar with the options for packaging rubygems as exes. If you or anyone else has suggestions or wants to submit a PR for this, I'd be glad to take a look.

**Comment by sergeevabc** [comment]
@frohoff, please check https://github.com/rdp/ruby_tutorials_core/wiki/ruby-talk-faq#ruby_to_exe
Especially, [rb2exe][1] looks relevant here, what do you think?

[1]: https://github.com/loureirorg/rb2exe

**Comment by frohoff** [comment]
Regarding rb2exe, https://github.com/loureirorg/rb2exe#todo seems to indicate that windows isn't supported yet and that it only supports building for Ruby 2.2.2. Most of the others on that list that I looked into seemed abandoned or broken, but I'm happy to look at others that look more promising. 

In the meantime I'm not aware of any reason one couldn't use ciphr by installing it via rubygems from a normal https://rubyinstaller.org/ windows ruby setup.

**Comment by sergeevabc** [comment]
>  I'm not aware of any reason one couldn't use Ciphr by installing…

Dependencies make tools awkward. Think of early firearms which required user to carry a heavy ramrod to push the projectile up against the gunpowder before shooting. Back to present day with its [challenges][1]: security tools are mostly in demand not by the academic milieu with all dependencies already in place or a willing to pollute system with ones, but by individuals on the go.

[1]: https://www.torproject.org/about/torusers.html.en
